---
name: "Release"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: "Generate build files"
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: 'linux/amd64, darwin/amd64, windows/amd64'
          name: 'go-http-proxy'
          compress: 'true'
          dest: 'dist'
      - name: "Generate Release"
        uses: softprops/action-gh-release@v1
        with:
          files: './dist/*'
          prerelease: false
          generate_release_notes: true

